# Generated by Django 3.2.5 on 2021-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=120)),
                ('doctor_info', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('hospital_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
    ]
